### PR TITLE
Fix header icons not showing in popup card preview in UI

### LINKED ISSUE #897: [Bug]: Header icon does not show in custom:popup-card preview
### My Home Assistant Version

Core: 2025.6.1
Frontend: 20250531.3
Browser Mod: 2.4.1

### What I am doing

Using new Header icon feature

### What I expect to happen

Icon show on perview in edit mode.

### What happened instead

No icon

### Minimal steps to reproduce

1. Create a header icon in settings

### Include any yaml code here

```YAML

```

### Error messages from the browser console

```console

```

### By checking each box below I indicate that I ...

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
- [x] If this issue is to do with an Android device losing connection, sensors becoming unavailable etc., please confirm you have read, understood and tried methods described in Wiki Article [Andoird Devices 'Always On'](https://github.com/thomasloven/hass-browser_mod/wiki/Andoird-Devices-'Always-On')

### PR DESCRIPTION
**Pull request by dcapslock**
Also tweaked styles of preview to match better those of popup. Styles needed to be adjusted anyhow to allow for header to be flex row. As it was, the title was not on the same line as the close icon.

Fixes #897

### CODE REVIEW

File: js/plugin/popups.ts [hunk 1]
```diff
@@ -345,7 +346,7 @@ class BrowserModPopup extends LitElement {
                           slot="actionItems"
                           title=${icon.title ?? ""}
                           @click=${() => { this.blur(); this._icon_action(index)} }
-                          class=${icon.class ?? ""}
+                          class=${ifDefined(icon.class)}
```
Comment (dcapslock) [inline js/plugin/popups.ts:349]: adjusting popupcode as well so class not added when class is not defined.

Comment (thomasloven) [reply js/plugin/popups.ts:349]: The correct way to do this is probably `classMap` https://lit.dev/docs/templates/directives/#classmap

**Review by thomasloven — APPROVED** [review]

File: js/plugin/popups.ts (hunk 1 above)
Comment (dcapslock) [reply js/plugin/popups.ts:349]: Updated to use class map. As class(es) will be a string, but `classMap = { classname: true }` I used a mapObject function, also filtering string split to remove empty strings which split returns when split character not found (empty string or string with 1 word).

Comment (thomasloven) [reply js/plugin/popups.ts:349]: Oh, right... then maybe ifDefined is better. Because that wasn't very pretty...

Comment (dcapslock) [reply js/plugin/popups.ts:349]: Yeah. I’m happy to revert.

Comment (dcapslock) [reply js/plugin/popups.ts:349]: Reverted
