### PR TITLE
Fix breaking old style action: call-service for _action config.

### LINKED ISSUE #869: [Bug]: confirmation in a nested window is broken
### My Home Assistant Version

Core: 2025.5.3
Frontend: 20250516.0

### What I am doing

Browser_mod version: 2.3.8
After the last update, confirmation of a nested window no longer works

### What I expect to happen

The action associated with the Yes button should be executed

### What happened instead

Clicking on the confirmation button does not happen

### Minimal steps to reproduce

1. I click the button
2. the pop-up opens
3. I click Yes
4. the pop-up disappears, but the associated action is not executed

### Include any yaml code here

```YAML
type: tile
entity: sensor.date
features_position: bottom
vertical: false
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Manutention
      content: Do you want to confirm?
      right_button: "Yes"
      right_button_action:
        action: call-service
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.roborock_s5_manutenzione
      left_button: "No"
```

### Error messages from the browser console

```console

```

### By checking each box below I indicate that I ...

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
- [x] If this issue is to do with an Android device losing connection, sensors becoming unavailable etc., please confirm you have read, understood and tried methods described in Wiki Article [Andoird Devices 'Always On'](https://github.com/thomasloven/hass-browser_mod/wiki/Andoird-Devices-'Always-On')

### PR DESCRIPTION
**Pull request by dcapslock**
Allows old style, after this style broke with changes in 2.3.6

```yaml
    action: call-service
    service: light.toggle
    data:
      entity_id: light.bed_light
```

fixes #869. This issue was closed by user with workaround, but there will likely be others waiting to upgrade that will be caught by this issue.

### CODE REVIEW

File: js/plugin/frontend-settings.ts [hunk 1]
```diff
@@ -212,6 +212,7 @@ export const AutoSettingsMixin = (SuperClass) => {
         }
         action_action.forEach(async (actionItem) => {
           var { action, service, target, data } = actionItem;
+          action = (action === "call-service" && service) || action;
           service = action ?? service;
```
Comment (thomasloven) [inline js/plugin/frontend-settings.ts]:
```suggestion
          service = (action === undefined || action === "call-service") ? service : action;
```

Comment (dcapslock) [reply js/plugin/frontend-settings.ts]: Thanks. I will give that a test.

Comment (dcapslock) [reply js/plugin/frontend-settings.ts]: Commited update
